--DROP TABLE SISGODBA.TMP_SBS_ANEXO6;

-->> Se usa para Importar los datos de los creditos con las modificaciones que realiza la sra. Coty

CREATE TABLE SISGODBA.TMP_SBS_ANEXO6
(
  NRO                    VARCHAR2(10 BYTE),
  APELLIDOPATERNO        VARCHAR2(120 BYTE),
  FECHANACIMIENTO        VARCHAR2(8 BYTE),
  SEXO                   VARCHAR2(1 BYTE),
  ESTADOCIVIL            VARCHAR2(1 BYTE),
  SIGLAEMPRESA           VARCHAR2(120 BYTE),
  CODIGOSOCIO            VARCHAR2(20 BYTE),
  PARTREGISTRAL          VARCHAR2(20 BYTE),
  TIPODOCIDENTIDAD       VARCHAR2(1 BYTE),
  DOCIDENTIDAD           VARCHAR2(12 BYTE),
  TIPOPERSONA            VARCHAR2(1 BYTE),
  DOMICILIO              VARCHAR2(300 BYTE),
  CALIFICACION           NUMBER,
  RELACLABORAL           NUMBER,
  CALIFALINEADA          NUMBER,
  CODIGOAGENCIA          VARCHAR2(2 BYTE),
  MONEDA                 VARCHAR2(2 BYTE),
  PERNROSOLICITUD        VARCHAR2(20 BYTE),
  TIPCREDITO             VARCHAR2(2 BYTE),
  SUBTIPCREDITO          VARCHAR2(2 BYTE),
  FECDESEMBOLSO          VARCHAR2(8 BYTE),
  MONTODESEMBOLSO        NUMBER(12,2),
  TASAINTANUAL           NUMBER(12,2),
  SALDO                  NUMBER(12,2),
  CUENTACONTABLE         VARCHAR2(20 BYTE),
  CAPITALVIGENTE         NUMBER(12,2),
  CAPITALREESTRUCTURADO  NUMBER(12,2),
  CAPITALREFINANCIADO    NUMBER(12,2),
  CAPITALVENCIDO         NUMBER(12,2),
  CAPITALJUDICIAL        NUMBER(12,2),
  CAPITALCONTINGENTE     NUMBER(12,2),
  CTACONCONTINGENTE      VARCHAR2(20 BYTE),
  DIASATRASO             NUMBER,
  GARANTIAPREF           NUMBER(12,2),
  GARAUT                 NUMBER(12,2),
  PROVISION              NUMBER(12,2),
  PROVCONST              NUMBER(12,2),
  SALDOCASTIGADOS        NUMBER(12,2),
  CTACONCASTIGADO        VARCHAR2(20 BYTE),
  INTXCOBRAR             NUMBER(12,2),
  INTSUSPENSO            NUMBER(12,2),
  INGRESOSDIFERIDOS      NUMBER(12,2),
  NOMPRODUCTO            VARCHAR2(100 BYTE),
  NUMCUOTAS              NUMBER,
  NROCUOPAGADAS          NUMBER,
  PERIODICIADAD          NUMBER,
  PERIODOGRACIA          NUMBER,
  FECVENCIMIENTO         VARCHAR2(8 BYTE),
  FECVENCIACTUAL         VARCHAR2(8 BYTE),
  CTACONREPROCOVID       VARCHAR2(20 BYTE)
)

TABLESPACE SISGO_DATOS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

GRANT DELETE, INSERT, SELECT, UPDATE ON SISGODBA.TMP_SBS_ANEXO6 TO ROL_SISGO;

SELECT * FROM TMP_SBS_ANEXO6 ORDER BY TO_NUMBER(NRO) ASC;