
----EXPORTAR ANEXO 6 CONCATENADO-------------
--Todos los campos concatenados
--Fecha se introduce en prompt, afecta cabecera y consulta

SELECT CADENA_TXT FROM (
        --Codificacion de la Cabecera
        ----CodFormato:       1106
        ----CodAnexo:         01
        ----CodSBS:           01116
        ----FechaReporte:     yyyymmdd
        ----ExprMonto:        012
        ----DatoControl:      0
        SELECT '11060101116' || TO_CHAR(TO_DATE(:P_FECHA,'DD/MM/RR'), 'yyyymmdd') || '0120' AS CADENA_TXT, 1 as id FROM TMP_SBS_ANEXO6_CFZ
    UNION
        --Consulta
        SELECT CADENA_TXT, 2 as id from (
        
SELECT
            LPAD(NRO, 6, ' ')  ||
            LPAD(REPLACE(REPLACE(COALESCE(APELLIDORAZONSOCIAL, ' '),CHR(10),''),CHR(13),''), 150, ' ') || -- NOMBRES en tabla person tienen salto de linea 2020-05-23
            LPAD(COALESCE(FECHANACIMIENTO, ' '), 8, ' ') ||
            REPLACE(GENERO,'0','O') || --PersonaJuridica = 'O' -- GCABALLERO, mejoras de Versión Anexo6 01/08/2019 -- P_GEN_SBS_ANEXO6
            REPLACE(ESTADOCIVIL,'0','O') || --PersonaJuridica = 'O' -- GCABALLERO, mejoras de Versión Anexo6 01/08/2019 -- P_GEN_SBS_ANEXO6
            LPAD(COALESCE(SIGLAEMPRESA, ' '), 30, ' ') ||
            LPAD(COALESCE(CODIGOSOCIO, ' '), 20, ' ') ||
            LPAD(COALESCE(PARTIDAREGISTRAL, ' '), 15, ' ') ||
            TIPODOCUMENTO ||
            LPAD(NRODOCUMENTO, 12, ' ') ||
            TIPOPERSONA ||
            LPAD(DOMICILIO, 150, ' ') ||
            LPAD(RELACLABORAL, 1, ' ') ||
            LPAD(CLASIFICACIONDEUDOR, 1, ' ') ||
            LPAD(CLASIFICACIONALINEADA, 1, ' ') ||
            LPAD(CODIGOAGENCIA, 3, ' ') ||
            LPAD(MONEDA, 2, '0') ||
            LPAD(NROCREDITO, 15, ' ') ||
            LPAD(COALESCE(TIPOCREDITO, ' '), 2, ' ') ||
            LPAD(COALESCE(SUBCREDITO, ' '), 2, ' ') ||
            LPAD(FECHADESEMBOLSO, 8, ' ') ||
            LPAD(ROUND(MONTODESEMBOLSADO * 100,0) , 18, ' ') ||
            LPAD(ROUND(TASAINTERESANUAL * 10000, 0), 6) ||
            LPAD(ROUND(SALDOCOLOCACION * 100,0), 18, ' ') ||
            LPAD(CUENTACONTABLE, 10, ' ') ||
            LPAD(ROUND(CAPITALVIGENTE * 100, 0), 18, ' ') ||
            LPAD(ROUND(CAPITALREESTRUCTURADO * 100, 0), 18, ' ') ||
            LPAD(ROUND(CAPITALREFINANCIADO * 100, 0), 18, ' ') ||
            LPAD(ROUND(CAPITALVENCIDO * 100, 0), 18, ' ') ||
            LPAD(ROUND(CAPITALJUDICIAL * 100, 0), 18, ' ') ||
            LPAD(ROUND(CAPITALCONTINGENTE * 100, 0), 18, ' ') ||
            LPAD(CUENTACONTINGENTE, 10, ' ') ||
            LPAD(DIASMORA, 8, ' ') ||
            LPAD(ROUND(SALDOGTIAPREFERIDA * 100, 0), 18, ' ') ||
            LPAD(ROUND(SALDOGTIAAUTOLIQUIDABLE * 100, 0), 18, ' ') ||
            LPAD(ROUND(PROVISIONREQUERIDA * 100, 0), 18, ' ') ||
            LPAD(ROUND(PROVISIONCONSTITUIDA * 100, 0), 18, ' ') ||
            LPAD(ROUND(SALDOSCASTIGADOS * 100, 0), 18, ' ') ||
            LPAD(CUENTACASTIGADO, 10, ' ') ||
            LPAD(ROUND(RENDIMIENTODEVENGADO * 100, 0), 18, ' ') ||
            LPAD(ROUND(INTERESSUSPENSO * 100, 0), 18, ' ') ||
            LPAD(ROUND(INGRESOSDIFERIDOS * 100, 0), 18, ' ') ||
            LPAD(TIPOPRODUCTO, 50, ' ') ||
            LPAD(NROCUOTASPROGRAMADAS, 6, ' ') ||
            LPAD(NROCUOTASPAGADAS, 6, ' ') ||
            LPAD(PERIODICIDADCUOTA, 6, ' ') ||
            LPAD(COALESCE(TO_CHAR(PERIODOGRACIA), ' '), 6, ' ') ||
            LPAD(FECHAVCTOORIGINAL, 8 , ' ') ||
            LPAD(FECHAVCTOACTUAL, 8, ' ') CADENA_TXT
 FROM
(
SELECT 
    NRO,
    APELLIDOPATERNO AS APELLIDORAZONSOCIAL,
    FECHANACIMIENTO AS FECHANACIMIENTO,
    SEXO AS GENERO,
    ESTADOCIVIL AS ESTADOCIVIL,
    SIGLAEMPRESA AS SIGLAEMPRESA,
    CODIGOSOCIO AS CODIGOSOCIO,
    PARTREGISTRAL AS PARTIDAREGISTRAL,
    TIPODOCIDENTIDAD AS TIPODOCUMENTO,
    DOCIDENTIDAD AS NRODOCUMENTO,
    TIPOPERSONA,
    DOMICILIO AS DOMICILIO,
    RELACLABORAL ,
    CALIFICACION AS CLASIFICACIONDEUDOR,
    CALIFALINEADA AS CLASIFICACIONALINEADA,
    CODIGOAGENCIA AS CODIGOAGENCIA,
    MONEDA AS MONEDA,
	TO_CHAR(PERNROSOLICITUD) AS NROCREDITO,
    TIPCREDITO AS TIPOCREDITO,
    SUBTIPCREDITO AS SUBCREDITO,
    FECDESEMBOLSO AS FECHADESEMBOLSO,
    MONTODESEMBOLSO AS MONTODESEMBOLSADO,
    TASAINTANUAL AS TASAINTERESANUAL,
    SALDO AS SALDOCOLOCACION,
    CUENTACONTABLE AS CUENTACONTABLE,
    CAPITALVIGENTE AS CAPITALVIGENTE,
    CAPITALREESTRUCTURADO AS CAPITALREESTRUCTURADO,
    CAPITALREFINANCIADO AS CAPITALREFINANCIADO,
    CAPITALVENCIDO AS CAPITALVENCIDO,
    CAPITALJUDICIAL AS CAPITALJUDICIAL,
    CAPITALCONTINGENTE AS CAPITALCONTINGENTE,
    CTACONCONTINGENTE AS CUENTACONTINGENTE,
    DIASATRASO AS DIASMORA,
    GARANTIAPREF AS SALDOGTIAPREFERIDA,
    GARAUT AS SALDOGTIAAUTOLIQUIDABLE,
    PROVISION AS PROVISIONREQUERIDA,
    PROVCONST AS PROVISIONCONSTITUIDA,
    SALDOCASTIGADOS AS SALDOSCASTIGADOS,
    CTACONCASTIGADO AS CUENTACASTIGADO,
    INTXCOBRAR AS RENDIMIENTODEVENGADO,
    INTSUSPENSO AS INTERESSUSPENSO,
    INGRESOSDIFERIDOS AS INGRESOSDIFERIDOS,
    NOMPRODUCTO AS TIPOPRODUCTO,
    NUMCUOTAS AS NROCUOTASPROGRAMADAS,
    NROCUOPAGADAS AS NROCUOTASPAGADAS,
    PERIODICIADAD AS PERIODICIDADCUOTA,
    PERIODOGRACIA AS PERIODOGRACIA,
    FECVENCIMIENTO AS FECHAVCTOORIGINAL,
    FECVENCIACTUAL AS FECHAVCTOACTUAL
FROM TMP_SBS_ANEXO6
     ) order by nro)
    UNION
        --Fin Sumas
        SELECT      RPAD('999999', 430) ||
                    LPAD(ROUND(SUM(MONTODESEMBOLSO) * 100, 0), 18) ||
                    LPAD(' ', 6) ||
                    LPAD(ROUND(SUM(SALDO), 18) * 100, 0) ||
                    LPAD(' ', 10) ||
                    LPAD(ROUND(SUM(CAPITALVIGENTE) * 100, 0), 18) ||
                    LPAD(ROUND(SUM(CAPITALREESTRUCTURADO) * 100, 0), 18) ||
                    LPAD(ROUND(SUM(CAPITALREFINANCIADO) * 100, 0), 18) ||
                    LPAD(ROUND(SUM(CAPITALVENCIDO) * 100, 0), 18) ||
                    LPAD(ROUND(SUM(CAPITALJUDICIAL) * 100, 0), 18) ||
                    LPAD(ROUND(SUM(CAPITALCONTINGENTE) * 100, 0), 18) ||
                    LPAD(' ', 10) ||
                    LPAD(' ', 8) ||
                    LPAD(ROUND(SUM(GARANTIAPREF) * 100, 0), 18) ||
                    LPAD(ROUND(SUM(GARAUT) * 100, 0), 18) ||
                    LPAD(ROUND(SUM(PROVISION) * 100, 0), 18) ||
                    LPAD(ROUND(SUM(PROVCONST) * 100, 0), 18) ||
                    LPAD(ROUND(SUM(SALDOCASTIGADOS) * 100, 0), 18) ||
                    LPAD(' ', 10) ||
                    LPAD(ROUND(SUM(INTXCOBRAR) * 100, 0), 18) ||
                    LPAD(ROUND(SUM(INTSUSPENSO) * 100, 0), 18) ||
                    LPAD(' ', 108) AS CADENA_TXT, 3 AS id
                FROM TMP_SBS_ANEXO6
    )
    ORDER BY id;
    